FROM {{ image_spec("ceilometer-base") }}
MAINTAINER {{ maintainer }}

RUN apt-get update \
    && apt-get install -y --no-install-recommends libvirt-dev \
    && /var/lib/microservices/venv/bin/pip install --upgrade libvirt-python prometheus_client

USER ceilometer

